# Use an official Python runtime as a parent image
FROM continuumio/anaconda

# Install any needed packages specified in requirements.txt
RUN conda update conda
RUN conda install -c conda-forge python-igraph 
RUN conda install networkx=1.11

# libiconv seems to be necessary for conda's python-igraph to work correctly
RUN conda install libiconv

RUN pip install tulip-python ndex-dev
RUN pip install git+git://github.com/michaelkyu/ddot.git@v1.0

RUN git clone -b 'v1.0' --single-branch --depth 1 https://github.com/michaelkyu/ddot.git ddot
RUN mv ddot/examples /ddot_examples
RUN rm -rf ddot
