# Use an official Python runtime as a parent image
FROM continuumio/anaconda3

# Install any needed packages specified in requirements.txt
RUN conda update conda
RUN conda install -c conda-forge python-igraph 
RUN conda install networkx=1.11

# For some reason, libiconv is needed for conda's python-igraph to work correctly
RUN conda install libiconv

RUN pip install tulip-python ndex-dev
RUN pip install git+git://github.com/michaelkyu/ddot.git@v1.0rc2