# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import cx_pb2 as cx__pb2


class CyServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StreamElements = channel.stream_stream(
        '/cxpb.CyService/StreamElements',
        request_serializer=cx__pb2.Element.SerializeToString,
        response_deserializer=cx__pb2.Element.FromString,
        )


class CyServiceServicer(object):

  def StreamElements(self, request_iterator, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CyServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StreamElements': grpc.stream_stream_rpc_method_handler(
          servicer.StreamElements,
          request_deserializer=cx__pb2.Element.FromString,
          response_serializer=cx__pb2.Element.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cxpb.CyService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
