#!/bin/bash

FILE=$1
THRESHOLD=$2
MIN_TERM_SIZE=$3
NUM_LEAVES=$4
OUTFILE=$5

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
grep Valid $FILE | awk -v i=$THRESHOLD -F "\t" '{if ($3 >= i) {print $2}}' | awk -F "," -v i=$MIN_TERM_SIZE 'NF > i' > $OUTFILE''_clusts.txt;

pushd .
cd $DIR
make clustersToDAG
popd
$DIR/clustersToDAG $OUTFILE''_clusts.txt $NUM_LEAVES > $OUTFILE;

